### ISSUE TITLE
"BEKOBUILD" について

### ISSUE THREAD

**Issue by sh19910711** [u-aizu/bekobrew#33]
##### 1. BEKOBUILD とは

YAMLで記述するビルドスクリプトです。
##### 2. 記述例

``` yaml
# comment
# ref: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gotty

# package info
name: gotty
version: 1.2
release: 1
desc: Go TTY - The Really Simple TTY Terminal Application
url: http://gotty.io

# source code & patch (which are downloaded and extracted into $srcdir)
sources:
  - https://github.com/gotty/gotty/releases/download/v$version/$name-$version.tar.xz
sums:
  - 78b5341e0fde2747dad05ebecf04e11d19b2a9984029418d594ae381caf0ec32

# shell script
build:
  - cd "$srcdir/$name-$version"
  - ./configure --prefix=/usr
  - make

# shell script
package:
  - cd "$srcdir/$name-$version"
  - make DESTDIR="$pkgdir" install
```
##### 3. 備考
- `sources` で指定されたファイルについて、展開可能であれば展開（well-knownな拡張子の場合）
- `$hoge` という記述で自分自身のパラメータや bekobrew 本体から与えられる情報（e.g., `$srcdir`, `$pkgdir`）にアクセスできると良い
- ビルド後に生成されるパッケージのファイル名は `$name-$version-$release-$arch.pkg.tar.gz`
##### 4. TODO
- [ ] パーサー実装
  - [LibYAML](http://pyyaml.org/wiki/LibYAML#ParserAPISynopsis)
